export const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

// 5 available rotor wirings (historically inspired)
export const ROTOR_WIRINGS: Record<number, string> = {
  1: 'DMTWSILRUYQNKFEJCAZBPGXOHV',
  2: 'HQZGPJTMOBLNCIFDYAWVEUSKRX',
  3: 'UQNTLSZFMREHDPXKIBVYGJCWOA',
  4: 'QJHGENLKZMDRPIFYXSTCWBAUOV',
  5: 'CIABORJXLHWMPFZSVDYEGNTKUQ',
};
